package web_experimentation

// URL Scope
const IS_EXACTLY = "IS_EXACTLY"
const IS_NOT_EXACTLY = "IS_NOT_EXACTLY"

const CONTAINS = "CONTAINS"
const DOES_NOT_CONTAINS = "DOES_NOT_CONTAINS"

const IS_REGULAR_EXPRESSION = "IS_REGULAR_EXPRESSION"
const IS_NOT_REGULAR_EXPRESSION = "IS_NOT_REGULAR_EXPRESSION"

const IS = "IS"
const IS_NOT = "IS_NOT"

const IS_SAVED_PAGE = "IS_SAVED_PAGE"
const IS_NOT_SAVED_PAGE = "IS_NOT_SAVED_PAGE"

// Selector Scope
const IS_SELECTOR_ID = "IS_SELECTOR_ID"
const IS_NOT_SELECTOR_ID = "IS_NOT_SELECTOR_ID"

const IS_SELECTOR_CLASS = "IS_SELECTOR_CLASS"
const IS_NOT_SELECTOR_CLASS = "IS_NOT_SELECTOR_CLASS"

const IS_SELECTOR_CUSTOM = "IS_SELECTOR_CUSTOM"
const IS_NOT_SELECTOR_CUSTOM = "IS_NOT_SELECTOR_CUSTOM"
