name: documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  docit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy the Readmes
        run: |
          cp ./README.md ./docs/index.md
          cp ./CONTRIBUTING.md ./docs
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Create a new branch
        run: |
          git checkout -b documentation
      - name: Make documentation
        run: |
          make doc
      - name: Commit changes
        run: |
          git add .
          git commit -m "Add changes" -a --allow-empty
      - name: Push branch to github
        run: |
          git push origin documentation
      - name: Create pull request changes
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PUBLISHER_TOKEN }}
          title: Update documentation

  deploy:
    needs: docit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
