name: documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  docit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy the Readmes
        run: |
          cp ./README.md ./docs/index.md
          cp ./CONTRIBUTING.md ./docs
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b doc
          git add .
          git commit -m "Add changes" -a --allow-empty
          git push origin doc
      - name: Create pull request changes
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PUBLISHER_TOKEN }}
          branch: doc
          base: main
          title: Update documentation

  deploy:
    needs: docit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
